defmodule BruceElixir.Hardware.Nerves do
  @moduledoc """
  Backend de build para dispositivos Nerves via `mix firmware`.

  Para placas Nerves (RPi, BeagleBone, etc.), executa:
      MIX_TARGET=<board> mix firmware

  As features selecionadas são traduzidas para config do Elixir
  e escritas em `config/nerves_features.exs`.
  """

  @behaviour BruceElixir.Hardware.Backend

  @nerves_targets [
    "bbb",
    "grisp2",
    "osd32mp1",
    "mangopi_mq_pro",
    "qemu_aarch64",
    "rpi",
    "rpi0",
    "rpi0_2",
    "rpi2",
    "rpi3",
    "rpi4",
    "rpi5",
    "x86_64"
  ]

  @nerves_display [
    %{id: "bbb", name: "BeagleBone Black", mcu: "ARM", vendor: "BeagleBoard"},
    %{id: "grisp2", name: "GRiSP 2", mcu: "ARM", vendor: "GRiSP"},
    %{id: "osd32mp1", name: "OSD32MP1", mcu: "ARM", vendor: "Octavo Systems"},
    %{id: "mangopi_mq_pro", name: "MangoPi MQ Pro", mcu: "RISC-V", vendor: "Sipeed"},
    %{id: "qemu_aarch64", name: "QEMU AArch64", mcu: "ARM", vendor: "QEMU"},
    %{id: "rpi", name: "Raspberry Pi (original)", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi0", name: "Raspberry Pi Zero", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi0_2", name: "Raspberry Pi Zero 2", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi2", name: "Raspberry Pi 2", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi3", name: "Raspberry Pi 3", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi4", name: "Raspberry Pi 4", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "rpi5", name: "Raspberry Pi 5", mcu: "ARM", vendor: "Raspberry Pi Foundation"},
    %{id: "x86_64", name: "x86-64 (generic)", mcu: "x86_64", vendor: "Generic"}
  ]

  @impl true
  def list_boards, do: @nerves_display

  @impl true
  def supports?(board_id), do: board_id in @nerves_targets

  @impl true
  def build(board_id, selected_features) do
    write_nerves_config(board_id, selected_features)

    publish(board_id, {:build_log, "\e[36m▶ Compilando #{board_id} com Nerves...\e[0m\n"})
    publish(board_id, {:build_log, "  Features: #{Enum.join(selected_features, ", ")}\n"})

    port =
      Port.open(
        {:spawn, "MIX_TARGET=#{board_id} mix firmware"},
        [:binary, :exit_status, cd: to_charlist(File.cwd!())]
      )

    result = stream_build(port, board_id)

    case result do
      :ok ->
        fw_path = Path.join(["_build", board_id, "dev", "nerves", "images", "bruce_elixir.fw"])

        publish(board_id, {:build_log, "\e[32m✔ Firmware Nerves criado\e[0m\n"})
        publish(board_id, {:build_log, "  Output: #{fw_path}\n"})
        publish(board_id, {:build_done, 0})
        :ok

      {:error, code} ->
        publish(board_id, {:build_log, "\e[31m✖ Build Nerves falhou (exit #{code})\e[0m\n"})
        publish(board_id, {:build_done, code})
        {:error, code}
    end
  end

  defp stream_build(port, board_id) do
    receive do
      {^port, {:data, data}} ->
        data
        |> String.split("\n")
        |> Enum.each(fn
          "" -> :ok
          line -> publish(board_id, {:build_log, "  \e[90m│\e[0m #{line}\n"})
        end)

        stream_build(port, board_id)

      {^port, {:exit_status, 0}} ->
        :ok

      {^port, {:exit_status, code}} ->
        {:error, code}
    end
  end

  @doc """
  Gera arquivo de config temporário com as features selecionadas
  para o build Nerves. O arquivo é importado pelo `config.exs`.
  """
  def write_nerves_config(board_id, selected_features) do
    config = generate_nerves_config(board_id, selected_features)
    config_path = "config/nerves_features.exs"
    File.write!(config_path, config)
    config_path
  end

  defp generate_nerves_config(_board_id, selected_features) do
    apps = feature_apps(selected_features)

    """
    # Generated by Bruce Firmware Installer — Nerves Feature Config
    import Config

    config :bruce_elixir, :nerves_features,
      enabled: #{inspect(selected_features)}

    # Extra applications for selected features
    # (uncomment and adjust when features are implemented)
    # config :bruce_elixir, :extra_applications,
    #   #{inspect(apps)}
    """
  end

  defp feature_apps(features) do
    Enum.map(features, &feature_to_app/1) |> Enum.reject(&is_nil/1)
  end

  defp feature_to_app("RTC"), do: :nerves_rtc
  defp feature_to_app("HAL"), do: :nerves_hw
  defp feature_to_app("TFT_eSPI"), do: :nerves_fb
  defp feature_to_app(_), do: nil

  defp publish(board_id, msg) do
    BruceElixir.PubSub.broadcast("build:#{board_id}", msg)
  rescue
    _ -> :ok
  end
end
