defmodule BruceElixir.Hardware.PlatformIO do
  @moduledoc """
  Backend de build para placas ESP32 via PlatformIO (`pio run`).

  Lê os JSONs de definição de placas em `src_bruce/boards/_boards_json/`,
  gera config INI com as build flags das features e executa `pio run -e <board>`.
  """

  @behaviour BruceElixir.Hardware.Backend

  @src_bruce "src_bruce"
  @boards_json "boards/_boards_json"

  @impl true
  def list_boards do
    @src_bruce
    |> Path.join(@boards_json)
    |> Path.join("*.json")
    |> Path.wildcard()
    |> Enum.map(fn path ->
      {:ok, json} = File.read(path)
      data = :json.decode(json)
      %{"name" => name, "build" => %{"mcu" => mcu}} = data
      board_name = path |> Path.basename(".json")
      %{id: board_name, name: name, mcu: mcu, vendor: data["vendor"]}
    end)
    |> Enum.sort_by(& &1.name)
  end

  @impl true
  def supports?(board_id) do
    path = @src_bruce |> Path.join(@boards_json) |> Path.join("#{board_id}.json")
    File.exists?(path)
  end

  @impl true
  def build(board_id, selected_features) do
    write_config(board_id, selected_features)

    publish(board_id, {:build_log, "\e[36m▶ Compilando #{board_id} com PlatformIO...\e[0m\n"})
    publish(board_id, {:build_log, "  Features: #{Enum.join(selected_features, ", ")}\n"})

    port =
      Port.open(
        {:spawn, "pio run -e #{board_id}"},
        [:binary, :exit_status, cd: to_charlist(@src_bruce)]
      )

    result = stream_build(port, board_id)

    case result do
      :ok ->
        publish(board_id, {:build_log, "\e[32m✔ Build concluído com sucesso\e[0m\n"})
        publish(board_id, {:build_done, 0})
        :ok

      {:error, code} ->
        publish(board_id, {:build_log, "\e[31m✖ Build falhou (exit #{code})\e[0m\n"})
        publish(board_id, {:build_done, code})
        {:error, code}
    end
  end

  defp stream_build(port, board_id) do
    receive do
      {^port, {:data, data}} ->
        data
        |> String.split("\n")
        |> Enum.each(fn
          "" -> :ok
          line -> publish(board_id, {:build_log, "  \e[90m│\e[0m #{line}\n"})
        end)

        stream_build(port, board_id)

      {^port, {:exit_status, 0}} ->
        :ok

      {^port, {:exit_status, code}} ->
        {:error, code}
    end
  end

  @doc false
  def write_config(board_id, selected_features) do
    flags = BruceElixir.Features.build_flags(selected_features)
    config = generate_extra_config(board_id, flags)
    config_path = Path.join(@src_bruce, "user_config_#{board_id}.ini")
    File.write!(config_path, config)
    config_path
  end

  defp generate_extra_config(board_id, flags) do
    """
    ; Generated by Bruce Firmware Installer
    [env:#{board_id}]
    build_flags =
        ${env:#{board_id}.build_flags}
        #{Enum.join(flags, "\n    ")}
    """
  end

  defp publish(board_id, msg) do
    BruceElixir.PubSub.broadcast("build:#{board_id}", msg)
  rescue
    _ -> :ok
  end
end
